# Generated by Django 4.1.3 on 2023-10-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_questionblock_create_questionblock_creator'),
        ('answers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_block', to='questions.questionblock'),
        ),
    ]
