# Generated by Django 4.1.3 on 2023-10-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_rename_active_time_questionblock_duration'),
        ('answers', '0003_answer_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_block', to='questions.questionblock'),
        ),
    ]
