# Generated by Django 4.1.3 on 2023-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionblock',
            name='context',
            field=models.ManyToManyField(related_name='block', to='contexts.context'),
        ),
    ]
