# Generated by Django 4.1.3 on 2023-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questionblock_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='importance',
            field=models.IntegerField(choices=[(1, 'High priority'), (2, 'Normal priority'), (3, 'Low important')], default=1),
        ),
    ]
