# Generated by Django 4.1.3 on 2023-09-24 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionblock_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 9, 24, 7, 18, 10, 513466, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='importance',
            field=models.IntegerField(choices=[(1, 'High priority'), (2, 'Normal priority'), (3, 'Low priority')], default=1),
        ),
    ]
