# Generated by Django 4.1.3 on 2023-09-24 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionblock_time_alter_questionblock_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionblock',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
