# Generated by Django 4.1.3 on 2023-09-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_questionblock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='days',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=5, null=True),
        ),
    ]
