# Generated by Django 4.1.3 on 2023-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questionblock_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionblock',
            name='frecuency',
            field=models.CharField(choices=[('O', 'Once'), ('D', 'Daily'), ('W', 'Weekly')], default='O', max_length=1),
        ),
    ]
