# Generated by Django 4.1.3 on 2023-10-09 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questionblock_frecuency'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
