# Generated by Django 4.1.3 on 2023-10-09 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_questionblock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionblock',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 10, 9, 15, 42, 18, 575584, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
