# Generated by Django 4.1.3 on 2023-10-09 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_questionblock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionblock',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
