# Generated by Django 4.1.3 on 2023-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_questionblock_create_questionblock_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='active_time',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
