# Generated by Django 4.1.3 on 2023-10-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_questionblock_active_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionblock',
            old_name='active_time',
            new_name='duration',
        ),
    ]
