# Generated by Django 4.1.3 on 2023-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_rename_active_time_questionblock_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='operating',
            field=models.BooleanField(default=False),
        ),
    ]
