# Generated by Django 4.1.3 on 2023-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriber',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
